# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('production_year', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pickuplocation', models.CharField(max_length=50)),
                ('dropofflocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=50, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rental',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('pickuplocation', models.CharField(max_length=50)),
                ('dropofflocation', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='carrentals.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carrentals.category'),
        ),
    ]
